#!/bin/bash
# post remove script

INST=('slow_feedback_server')

if [[ "purge" == "$1" || "remove" == "$1" ]]; then
   for i in "${INST[@]}"; do
      /export/doocs/server/doocs stop "$i" || true
   done
fi

if [[ "purge" == "$1" ]] ; then
   for i in "${INST[@]}"; do
      # check if this server is in the watchdog
      INWD=$( grep "/server/$i/" /export/doocs/server/watchdog_server/watchdog_server.conf || true )
      if [[ -n "${INWD}" ]]; then
         /export/doocs/server/doocs delete "$i" || true
      fi
      # remove entire server directory
      rm -rf /export/doocs/server/"$i"
   done
fi
