#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-bcm-server package

set -e

case "$1" in
    configure)
        # continue as normal
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
export CFGDIR=/usr/share/ConfigGenerator-bcm-config-#epochdashversion# 
/usr/share/ConfigGenerator#dependency-epochversion-doocs-llrfctrlconfig-generator#/configureCurrentHost.sh bcm-server

# make the template-generated scripts executable
. $CFGDIR/.stationSettings.sh
DIR=${SETTINGS['WORKDIR']}   
chmod +x $DIR/*.sh $DIR/*.py
