#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-tel-server package

#set -e

case "$1" in
  configure)
    # continue as normal
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0;
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2;
    exit 0;
  ;;
esac

# 
# install the new server
ln -snf /export/doocs/server/trip_event_logger/trip_event_logger.dist /export/doocs/server/trip_event_logger/trip_event_logger

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-trip-event-logger-config-01-00/configureThisHost.sh tel
