#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-llrfpiezo-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

# 
# install the new server
ln -snf /export/doocs/server/llrfPiezo_server/llrfPiezo_server.dist /export/doocs/server/llrfPiezo_server/llrfPiezo_server

#
# generate and/or update configuration files
ConfigGeneratorVersion=`echo 01-07 | sed -e 's|-|.|' -e 's|-||'`
/usr/share/llrfConfigGenerator${ConfigGeneratorVersion}/configureCurrentHost.sh llrfpiezo
