#!/bin/bash -e
# post install script 
set -e

case "$1" in
  configure)
    # continue as normal
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0;
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2;
    exit 0;
  ;;
esac

# 
# install the new server
# create dir if it doesn't exists.
mkdir -p /export/doocs/server/flash-dism-generic-server


ln -sfn /usr/bin/doocs-generic-chimeratk-server /export/doocs/server/flash-dism-generic-server/flash-dism-generic-server

# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
CFGDIR=/usr/share/ConfigGenerator-doocs-flash-dism-server-config-#epochdashversion# /usr/share/ConfigGenerator#dependency-epochversion-config-generator-scripts#/configureCurrentHost.sh flash-dism-generic-server
