#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-steppermotor-server package

#set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

ln -sfn /export/doocs/server/steppermotorserver/bin/steppermotorserver /export/doocs/server/steppermotorserver/steppermotorserver

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-ChimeraTK_StepperMotor-config-01-00/configureThisHost.sh steppermotor
