#!/bin/bash -e
# post install script for the Debian GNU/Linux tarla-llrfctrl-server package

set -e

case "$1" in
    configure)
        # continue as normal
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

#
# generate and/or update configuration files.
/usr/share/ConfigGenerator-llrfctrl_server-hzb-config-#epochdashversion#/configureThisHost.sh llrfctrl-epics
