#!/bin/sh
# post install script for the Debian GNU/Linux doocs-llrfpiezo-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

##### make the /export/<nodename> linl ###########
NODENAME=`uname -n`
UNODENAME=`uname -n | sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" `

#
# RPC_LIBNO
# 
if [ -f /export/doocs/server/llrfPiezo_server/RPC_LIBNO ] ; then
RPC_LIBNO=`cat /export/doocs/server/llrfPiezo_server/RPC_LIBNO`
export RPC_LIBNO
else
  echo 2>&1 "File: /export/doocs/server/llrfPiezo_server/RPC_LIBNO is missing"
  exit 1
fi

#
# Install server config file template, if no config file exists
#
if [ ! -f /export/doocs/server/llrfPiezo_server/llrfPiezo_server.conf  ] ; then
   if [ -f /export/doocs/server/llrfPiezo_server/llrfPiezo_CONF.TEMPLATE ] ; then
      cat /export/doocs/server/llrfPiezo_server/llrfPiezo_CONF.TEMPLATE |         \
           sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" >   \
           /export/doocs/server/llrfPiezo_server/llrfPiezo_server.conf
      chown doocsadm.doocsadm /export/doocs/server/llrfPiezo_server/llrfPiezo_server.conf
   else
       echo "!!! no llrfPiezo_CONF.TEMPLATE file found !!! "
   fi
fi

##
## watchdog template 
##
if [ -f /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE ] ; then
   cat /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE | \
      sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" | \
      sed -e "s/servername/llrfPiezo_server/g" | \
      sed -e "s/SERVERNAME/LLRFPIEZO/g" | \
      sed -e "s/SERVERLIBNO/$RPC_LIBNO/g" > \
      /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.llrfPiezo
fi 

##
## ens
##
echo "add server to ens "
echo "RPC_LIBNO = $RPC_LIBNO"

#
# stop the old server server if running
/export/doocs/server/doocs stop llrfPiezo_server || true

#
# move the running server to old
if [ -f /export/doocs/server/llrfPiezo_server/llrfPiezo_server ] ; then
   if [ -f /export/doocs/server/llrfPiezo_server/llrfPiezo_server.OLD ] ; then
      rm /export/doocs/server/llrfPiezo_server/llrfPiezo_server.OLD
   fi
   mv /export/doocs/server/llrfPiezo_server/llrfPiezo_server /export/doocs/server/llrfPiezo_server/llrfPiezo_server.OLD
fi

# 
# install the new server
cp -a /export/doocs/server/llrfPiezo_server/llrfPiezo_server.dist /export/doocs/server/llrfPiezo_server/llrfPiezo_server

# change ownership of the server directory and all files in it
chown -R doocsadm:doocsadm /export/doocs/server/llrfPiezo_server

#
# add the server to the watchdog, if not yet in
INWD=`grep "/server/llrfPiezo_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
if [ -z "${INWD}" ] ; then
   /export/doocs/server/doocs add llrfPiezo_server || true
fi

