#!/bin/sh
# post remove script for the Debian GNU/Linux doocs-beam-regions-reset-server package

if [ "purge" = "$1" -o "remove" = "$1" ] ; then
   /export/doocs/server/doocs stop beam_regions_reset_server || true
fi

if [ "purge" = "$1" ] ; then
   # check if this server is in the watchdog
   INWD=`grep "/server/beam_regions_reset_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
   if [ -n "${INWD}" ] ; then
      /export/doocs/server/doocs delete beam_regions_reset_server || true
   fi
   # remove entire server directory
   rm -rf /export/doocs/server/beam_regions_reset_server
fi
