#!/bin/sh
# post remove script for the Debian GNU/Linux doocs-itcf-server package

if [ "purge" = "$1" -o "remove" = "$1" ] ; then
   # check if this server is already in the watchdog
   INWD=`grep "/server/itcf_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
   if [ -n "${INWD}" ] ; then
      /export/doocs/server/doocs delete itcf_server || true
   fi
   /export/doocs/server/doocs stop itcf_server || true
fi

if [ "purge" = "$1" ] ; then
   /export/doocs/server/doocs delete itcf_server || true
   rm -rf /export/doocs/server/itcf_server
fi
