#!/bin/bash
# post install script for the Debian GNU/Linux doocs-sdm-server package

set -e

case "$1" in
    configure)
    # continue as normal
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

########## make the /export/<nodename> linl ######################
NODENAME=`uname -n`
UNODENAME=`uname -n | sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" `
#
# RPC_LIBNO
#
RPCNOBAM=610593146
RPCNOEOD=610493146
POS=`expr index $UNODENAME CPU`
UFACILITY_NAME=${UNODENAME:0:POS-1}
FACILITY_NAME=${NODENAME:0:POS-1}
DOOCS_FACILITY_NAME=$UFACILITY_NAME.SDIAG

if [ "$FACILITY_NAME" == "xfel" ]; then
    GID_OPERATOR=514
    GIT_EXPERT=514
elif [ "$FACILITY_NAME" == "flash" ];  then
    GID_OPERATOR=422
    GIT_EXPERT=414
fi

if [ "$NODENAME" == "xfelcpusd47i1" ] ; then
    LOCATION='47.I1'
    DEVICE_NAME='BAM'
    RPCNO=$RPCNOBAM
fi
if [ "$NODENAME" == "xfelcpusd51i1" ] ; then
    LOCATION='51.I1'
    DEVICE_NAME='EOD'
    RPCNO=610493146
    TMCB_ADDRESS='xfeltmcbeod51i1'
fi
if [ "$NODENAME" == "xfelcpusd181b1" ] ; then
    LOCATION='181.B1'
    LOCATIONEOD='179.B1'
    DEVICE_NAME='BAM'
    RPCNO=$RPCNOBAM
    TMCB_ADDRESS='xfeltmcbeod179b1'
fi
if [ "$NODENAME" == "xfelcpusd205b1" ] ; then
    LOCATION='203.B1'
    LOCATIONEOD='204.B1'
    DEVICE_NAME='BAM'
    RPCNO=$RPCNOBAM
    TMCB_ADDRESS='xfeltmcbeod204b1'
fi
if [ "$NODENAME" == "xfelcpusd392b2" ] ; then
    LOCATION='392.B2'
    DEVICE_NAME='BAM'
    RPCNO=$RPCNOBAM
fi
if [ "$NODENAME" == "xfelcpusd417b2" ] ; then
    LOCATION='414.B2'
    DEVICE_NAME='BAM'
    RPCNO=$RPCNOBAM
fi

if [ "$NODENAME" == "xfelcpulltdsi1" ] ; then
    LOCATION="52.I1"
    DEVICE_NAME="TDS"
    RPCNO=$RPCNOBAM
    TMCB_ADDRESS='xfeltmcbtds52i1'
fi

if [ "$NODENAME" == "flashcpullbacca" ]; then
    LOCATION='BACCA'
    DEVICE_NAME='BACCA'
    RPCNO=$RPCNOBAM
    TMCB_ADDRESS='flashtmcbfgmbacca'
fi

if [ ! -f /export/doocs/server/sdm_server/sdm_server.conf  ] ; then
    if [ -f /export/doocs/server/sdm_server/sdm_CONF.TEMPLATE ] ; then
        cat /export/doocs/server/sdm_server/sdm_CONF.TEMPLATE | \
            sed "s/LOCATION/$LOCATION/g" | \
            sed "s/DOOCS_FACILITY_NAME/$DOOCS_FACILITY_NAME/g" | \
            sed "s/NODENAME/$UNODENAME/g" | \
            sed "s/DEVICE_NAME/$DEVICE_NAME/g" | \
            sed "s/RPCNO/$RPCNO/g"| \
            sed "s/GID_OPERATOR/$GID_OPERATOR/g" | \
            sed "s/GIT_EXPERT/$GIT_EXPERT/g" | \
            sed "s/nodename/$NODENAME/g" > \
                /export/doocs/server/sdm_server/sdm_server.conf
    fi
    case "${NODENAME}" in
        "xfelcpusd51i1" | "xfelcpulltdsi1" | "flashcpullbacca")
            echo "SDM  sdm://./rebot=$TMCB_ADDRESS,5001 eod.map" >> /export/doocs/server/sdm_server/sdm.dmap
            sed /export/doocs/server/sdm_server/sdm_server.conf --in-place \
                -e "/${LOCATION}.OPTICAL_SWITCH/I, +22 d"
            ;;
        *)
            echo 'SDM /dev/pcieunis4 bam.map' > /export/doocs/server/sdm_server/sdm.dmap
            ;;
    esac
fi

#
# move the running server to old
if [ -f /export/doocs/server/sdm_server/sdm_server ] ; then
    if [ -f /export/doocs/server/sdm_server/sdm_server.OLD ] ; then
        rm /export/doocs/server/sdm_server/sdm_server.OLD
    fi
    mv /export/doocs/server/sdm_server/sdm_server /export/doocs/server/sdm_server/sdm_server.OLD
fi
# 
# install the new server
cp -a /export/doocs/server/sdm_server/sdm_server.dist \
   /export/doocs/server/sdm_server/sdm_server

# change owership
chown -R doocsadm:doocsadm /export/doocs/server/sdm_server

if [ -f /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE ] ; then
    cat /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE | \
        sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" | \
        sed -e "s/servername/sdm_server/g" | \
        sed -e "s/SERVERNAME/SDM/g" | \
        sed -e "s/SERVERLIBNO/$RPCNOBAM/g" > \
            /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.sdm
    chown doocsadm:doocsadm /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.sdm
    #
    # check if this server is already in the watchdog
    INWD=`grep "/server/sdm_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`

    if [ -z "${INWD}" ] ; then
      /export/doocs/server/doocs add sdm_server || true
    fi
fi

#
# kill the server if there is a valid PID file and 
# a AUTORESTART flag in the server dir
if [ -f /export/doocs/server/sdm_server/sdm_server.PID ] ; then
    SPID=`cat /export/doocs/server/sdm_server/sdm_server.PID`
    if [ -d /proc/${SPID} ] ; then
        /export/doocs/server/doocs restart sdm_server
    else
        echo "sdm_server: postinstall remove not valid PID file"
        rm /export/doocs/server/sdm_server/sdm_server.PID
    fi
fi

#install second 
if [ "$NODENAME" == "xfelcpusd181b1" -o "$NODENAME" == "xfelcpusd205b1" ] ; then
    if [ ! -d /export/doocs/server/sdm_eod_server ] ; then
        mkdir /export/doocs/server/sdm_eod_server
        ln -sfn /export/doocs/server/sdm_server/sdm_server /export/doocs/server/sdm_eod_server/sdm_eod_server
        ln -sfn /export/doocs/server/sdm_server/eod.map /export/doocs/server/sdm_eod_server/eod.map
        if [ ! -f /export/doocs/server/sdm_eod_server/sdm_eod_server.conf  ] ; then
            if [ -f /export/doocs/server/sdm_server/sdm_CONF.TEMPLATE ] ; then
                cat /export/doocs/server/sdm_server/sdm_CONF.TEMPLATE | \
                    sed "/LOCATION.OPTICAL_SWITCH/I, +22 d" | \
                    sed "s/LOCATION/$LOCATIONEOD/g" | \
                    sed "s/DOOCS_FACILITY_NAME/$DOOCS_FACILITY_NAME/g" | \
                    sed "s/NODENAME/$UNODENAME/g" | \
                    sed "s/DEVICE_NAME/EOD/g" | \
                    sed "s/RPCNO/$RPCNOEOD/g"| \
                    sed "s/GID_OPERATOR/$GID_OPERATOR/g" | \
                    sed "s/GIT_EXPERT/$GIT_EXPERT/g" | \
                    sed "s/nodename/$NODENAME/g" | \
                    sed "s/sdm_server/sdm_eod_server/g" > \
                /export/doocs/server/sdm_eod_server/sdm_eod_server.conf
            fi
        fi
        echo "SDM  sdm://./rebot=$TMCB_ADDRESS,5001 eod.map" >> /export/doocs/server/sdm_eod_server/sdm.dmap
    fi

    # change owership
    chown -R doocsadm:doocsadm /export/doocs/server/sdm_eod_server
    
    if [ -f /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE ] ; then
        cat /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE | \
            sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" | \
            sed -e "s/servername/sdm_eod_server/g" | \
            sed -e "s/SERVERNAME/SDM_EOD/g" | \
            sed -e "s/SERVERLIBNO/$RPCNOEOD/g" > \
                /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.sdm_eod
        chown doocsadm:doocsadm /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.sdm_eod
        #
        # check if this server is already in the watchdog
        INWD=`grep "/server/sdm_eod_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`

        if [ -z "${INWD}" ] ; then
            /export/doocs/server/doocs add sdm_eod_server || true
        fi
    fi

    #
    # kill the server if there is a valid PID file and 
    # a AUTORESTART flag in the server dir
    if [ -f /export/doocs/server/sdm_eod_server/sdm_eod_server.PID ] ; then
        SPID=`cat /export/doocs/server/sdm_eod_server/sdm_eod_server.PID`
        if [ -d /proc/${SPID} ] ; then
            /export/doocs/server/doocs restart sdm_eod_server
        else
            echo "sdm_eod_server: postinstall remove not valid PID file"
            rm /export/doocs/server/sdm_eod_server/sdm_eod_server.PID
        fi
    fi

fi
