#!/bin/bash
# post remove script for the Debian GNU/Linux doocs-sdm-server package

NODENAME=`uname -n`

if [ "purge" == "$1" -o "remove" == "$1" ] ; then
    # check if this server is already in the watchdog
    INWD=`grep "/server/sdm_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
    echo $INWD
    if [ -n "${INWD}" ] ; then
	/export/doocs/server/doocs delete sdm_server || true
    fi
fi

if [ "purge" = "$1" ] ; then
    rm -rf /export/doocs/server/sdm_server
    rm /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.sdm
fi

if [ "$NODENAME" == "xfelcpusd181b1" -o "$NODENAME" == "xfelcpusd205b1" ] ; then
    if [ "purge" == "$1" -o "remove" == "$1" ] ; then
	# check if this server is already in the watchdog
	INWD=`grep "/server/sdm_eod_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
	if [ -n "${INWD}" ] ; then
	    /export/doocs/server/doocs delete sdm_eod_server || true
	fi
    fi

    if [ "purge" == "$1" ] ; then
	rm -rf /export/doocs/server/sdm_eod_server
	rm /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.sdm_eod
    fi
fi
