#!/bin/sh
# post remove script for the Debian GNU/Linux doocs-sdm-server package

if [ "purge" = "$1" -o "remove" = "$1" ] ; then
    # check if this server is already in the watchdog
    INWD=`grep "/server/sdm_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
    if [ -n "${INWD}" ] ; then
	/export/doocs/server/doocs delete sdm_server || true
    fi
    /export/doocs/server/doocs stop sdm_server || true
fi

if [ "purge" = "$1" ] ; then
    rm -rf /export/doocs/server/sdm_server
fi

if [ "$NODENAME" == "xfelcpusd181b1" -o "$NODENAME" == "xfelcpusd205b1" ] ; then
    if [ "purge" = "$1" -o "remove" = "$1" ] ; then
	# check if this server is already in the watchdog
	INWD=`grep "/server/sdm_eod_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
	if [ -n "${INWD}" ] ; then
	    /export/doocs/server/doocs delete sdm_eod_server || true
	fi
	/export/doocs/server/doocs stop sdm_eod_server || true
    fi

    if [ "purge" = "$1" ] ; then
	rm -rf /export/doocs/server/sdm_eod_server
    fi
fi
