#!/bin/bash -e
# post install script 
set -e

case "$1" in
  configure)
    # continue as normal
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0;
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2;
    exit 0;
  ;;
esac

# 
# install the new server
# create dir if it doesn't exists.
mkdir -p foo /export/doocs/server/logm-generic-server


ln -sfn /usr/bin/doocs-generic-chimeratk-server /export/doocs/server/logm-generic-server/logm-generic-server

# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-doocs-logm-generic-server-config-#epochdashversion#/configureThisHost.sh logm-generic-server
