#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-bam-server package

set -e

case "$1" in
    configure)
        # continue as normal
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

#
# install the new server
ln -snf /export/doocs/server/tec_server/bin/tec_server /export/doocs/server/tec_server/tec_server

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-tec-config-02-00/configureThisHost.sh tec
