#!/bin/sh
# post install script for the ChimeraTK watchdog package

# create links to config files that are needed for running the server
if [ ! -e "/var/lib/chimeratk" ]; then
 mkdir /var/lib/chimeratk/
fi
# should not exist but better check that here
if [ ! -e "/var/lib/chimeratk/watchdog-server" ]; then
	mkdir /var/lib/chimeratk/watchdog-server/
fi
if [ -e "/etc/chimeratk/watchdog-server/WatchdogServer_mapping.xml" ] && [ ! -e "/var/lib/chimeratk/watchdog-server/WatchdogServer_mapping.xml" ]; then
	ln -s /etc/chimeratk/watchdog-server/WatchdogServer_mapping.xml /var/lib/chimeratk/watchdog-server/
fi
if [ -e "/etc/chimeratk/watchdog-server/WatchdogServerConfig.xml" ] && [ ! -e "/var/lib/chimeratk/watchdog-server/WatchdogServerConfig.xml" ]; then
	ln -s /etc/chimeratk/watchdog-server/WatchdogServerConfig.xml /var/lib/chimeratk/watchdog-server/
fi
if [ -e "/etc/chimeratk/watchdog-server/chimeratk-watchdog.service" ] && [ ! -e "/var/lib/chimeratk/watchdog-server/chimeratk-watchdog.service" ]; then
	ln -s /etc/chimeratk/watchdog-server/chimeratk-watchdog.service /var/lib/chimeratk/watchdog-server/
fi
if [ -d "/lib/systemd/system" -a -x "/bin/systemctl" ] ; then
   systemctl daemon-reload
   # no need to perform stop or disable before, since with every installation an old version is uninstalled and prerm is executed 
   systemctl enable /var/lib/chimeratk/watchdog-server/chimeratk-watchdog.service
   systemctl start chimeratk-watchdog.service
fi

# recover old persist file and keep e.g. user and group settings
if [ -e "/etc/chimeratk/watchdog-server/WatchdogServer.persist" ]; then
	rsync -a /etc/chimeratk/watchdog-server/WatchdogServer.persist /var/lib/chimeratk/watchdog-server
fi

#create variable tree file
cd /etc/chimeratk/watchdog-server/
/usr/bin/watchdog-server-xmlGenerator


