#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-dism-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

##### make the /export/<nodename> linl ###########
NODENAME=`uname -n`
UNODENAME=`uname -n | sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" `

#
# ACCELERATOR
#
if [ ${NODENAME:0:6} == "xfelml" ] || [ ${NODENAME:0:9} == "xfelcpull" ];then
  ACCELERATOR="XFEL"
elif [ ${NODENAME:0:7} == "flashml" ] || [ ${NODENAME:0:10} == "flashcpull" ] || [ ${NODENAME:0:9} == "mskcpuacc" ];then
  ACCELERATOR="FLASH"
else
  echo 2>&1 "Cannot determine accelerator"
  ACCELERATOR="ACCELERATORNAME"
  #exit 1
fi

#
# RPC_LIBNO
# 
if [ -f /export/doocs/server/dism_server/RPC_LIBNO ] ; then
RPC_LIBNO=`cat /export/doocs/server/dism_server/RPC_LIBNO`
export RPC_LIBNO
else
  echo 2>&1 "File: /export/doocs/server/dism_server/RPC_LIBNO is missing"
  exit 1
fi

# Note: The old config stuff has been removed. The server is written with the current style.

if [ ! -f /export/doocs/server/dism_server/dism_server.conf  ] ; then
   if [ -f /export/doocs/server/dism_server/dism_CONF.TEMPLATE ] ; then
      cat /export/doocs/server/dism_server/dism_CONF.TEMPLATE | \
       sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g"| \
       sed -e "s/ACCELERATOR/$ACCELERATOR/g" > \
       /export/doocs/server/dism_server/dism_server.conf
      chown doocsadm.doocsadm /export/doocs/server/dism_server/dism_server.conf
   else
       echo "!!! no dism template !!! "
   fi
fi

##
## watchdog template 
##
if [ -f /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE ] ; then
   cat /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE | \
      sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" | \
      sed -e "s/servername/dism_server/g" | \
      sed -e "s/SERVERNAME/DISM/g" | \
      sed -e "s/SERVERLIBNO/$RPC_LIBNO/g" > \
      /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.dism
fi 

#
# move the running server to old
if [ -f /export/doocs/server/dism_server/dism_server ] ; then
   if [ -f /export/doocs/server/dism_server/dism_server.OLD ] ; then
      rm /export/doocs/server/dism_server/dism_server.OLD
   fi
   mv /export/doocs/server/dism_server/dism_server /export/doocs/server/dism_server/dism_server.OLD
fi
# 
# install the new server
cp -a /export/doocs/server/dism_server/dism_server.dist /export/doocs/server/dism_server/dism_server

#
# check if this server is already in the watchdog
INWD=`grep "/server/dism_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`

if [ -z "${INWD}" ] ; then
   /export/doocs/server/doocs add dism_server || true
fi

#
# stop the server (just in case it is already running)
# It has to be off while the config is being updated.
/export/doocs/server/doocs stop  dism_server || true
#

# change ownership of the server directory and all files in it
chown -R doocsadm:doocsadm /export/doocs/server/dism_server

#
# restart the server
/export/doocs/server/doocs restart dism_server
