#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-llrfctrlsrf-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

# 
# install the new server
ln -snf /export/doocs/server/llrfCtrl_server/llrfCtrl_server.dist /export/doocs/server/llrfCtrl_server/llrfCtrl_server

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
ConfigGeneratorVersion=`echo 01-06 | sed -e 's|-|.|' -e 's|-||'`
/usr/share/llrfConfigGenerator${ConfigGeneratorVersion}/configureCurrentHost.sh llrfctrl
