#!/bin/bash
case "$1" in
  configure)
    # continue as normal
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0;
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2;
    exit 0;
  ;;
esac
which pip3
which pip
locate pip3
locate pip
pip3 install robotframework==3.0
exit 0
