#!/bin/bash -e
# post install script 
set -e

case "$1" in
  configure)
    # continue as normal
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0;
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2;
    exit 0;
  ;;
esac

# 
# install the new server
ln -sfn /usr/bin/doocs-generic-chimeratk-server#epochdashversion# /export/doocs/server/mo-generator1300_server/mo-generator1300_server

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
CFGDIR=/usr/share/ConfigGenerator-mo-synth-generic-server-config-#epochdashversion# /usr/share/ConfigGenerator#dependency-epochversion-doocs-llrfctrlconfig-generator#/configureCurrentHost.sh mo-synth-generic-server
