#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-llrfdiagnostic-server package

#set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

# 
# install the new server
ln -snf /export/doocs/server/llrf_diagnostic_server/llrf_diagnostic_server.dist /export/doocs/server/llrf_diagnostic_server/llrf_diagnostic_server

ConfigGeneratorVersion=`echo #UseConfigGeneratorVersion# | sed -e 's|-|.|' -e 's|-||'`
/usr/share/llrfConfigGenerator${ConfigGeneratorVersion}/configureCurrentHost.sh llrf-diagnostic
