#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-beam-regions-reset-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-beam-regions-reset-server-config-#epochdashversion#/configureThisHost.sh beam-regions-reset-server
