#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-psm-ctrl-server package

#set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

########## make the /export/<nodename> linl ######################
NODENAME=`uname -n`
UNODENAME=`uname -n | sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" `

#
# RPC_LIBNO
# 
if [ -f /export/doocs/server/psm_ctrl_server/RPC_LIBNO ] ; then
RPC_LIBNO=`cat /export/doocs/server/psm_ctrl_server/RPC_LIBNO`
export RPC_LIBNO
else
  echo 2>&1 "File: /export/doocs/server/psm_ctrl_server/RPC_LIBNO is missing"
  exit 1
fi

###
### watchdog template 
###
if [ -f /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE ] ; then
   cat /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE | \
      sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" | \
      sed -e "s/servername/psm_ctrl_server/g" | \
      sed -e "s/SERVERNAME/PSM/g" | \
      sed -e "s/SERVERLIBNO/$RPC_LIBNO/g" > \
      /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.psm
fi 

#
# move the running server to old
if [ -f /export/doocs/server/psm_ctrl_server/psm_ctrl_server ] ; then
   if [ -f /export/doocs/server/psm_ctrl_server/psm_ctrl_server.OLD ] ; then
      rm /export/doocs/server/psm_ctrl_server/psm_ctrl_server.OLD
   fi
   mv /export/doocs/server/psm_ctrl_server/psm_ctrl_server /export/doocs/server/psm_ctrl_server/psm_ctrl_server.OLD
fi
# 
# install the new server
cp -a /export/doocs/server/psm_ctrl_server/psm_ctrl_server.dist /export/doocs/server/psm_ctrl_server/psm_ctrl_server

#
# check if this server is already in the watchdog
INWD=`grep "/server/psm_ctrl_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`

if [ -z "${INWD}" ] ; then
   /export/doocs/server/doocs add psm_ctrl_server || true
fi

#
# stop the server (just in case it is already running)
# It has to be off while the config is being updated.
/export/doocs/server/doocs stop  psm_ctrl_server || true

#
# generate and/or update configuration files
ConfigGeneratorVersion=`echo #UseConfigGeneratorVersion# | sed -e 's|-|.|' -e 's|-||'`
if ! /usr/share/llrfConfigGenerator${ConfigGeneratorVersion}/generateConfigForCurrentHost.sh psm ; then
  echo "cannot configure the server, please do it manually"
  exit 0
fi   
 

#
# change ownership of the server directory and all files in it
chown -R doocsadm:doocsadm /export/doocs/server/psm_ctrl_server

#
# restart the server
/export/doocs/server/doocs restart psm_ctrl_server
