#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-ulog-ctrl-server package

set -e

case "$1" in
  configure)
    # continue as normal
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0;
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2;
    exit 0;
  ;;
esac

# 
# install the new server
ln -snf /export/doocs/server/logm_ctrl_server/logm_ctrl_server.dist /export/doocs/server/logm_ctrl_server/logm_ctrl_server

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
CFGDIR=/usr/share/ConfigGenerator-logm-ctrl-config-00-05 /usr/share/ConfigGenerator02.00/configureCurrentHost.sh llrf-logm
