#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-eod-server package

set -e

case "$1" in
    configure)
        # continue as normal
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
export CFGDIR=/usr/share/ConfigGenerator-eod-config-#epochdashversion# 
/usr/share/ConfigGenerator#dependency-epochversion-config-generator-scripts#/config myself --type eod


# make the template-generated scripts executable
DIR=/export/doocs/server/eod_server
shopt -s nullglob
for a in $DIR/*.sh $DIR/*.py; do
	chmod +x "$a"
done
