#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-dcm-ctrl-server package

set -e

case "$1" in
    configure)
        # continue as normal
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-dcmctrl-config-08-02/configureThisHost.sh dcmctrl

# make the template-generated scripts executable
DIR=/export/doocs/server/dcm_ctrl_server/
shopt -s nullglob
for a in $DIR/*.sh $DIR/*.py; do
	chmod +x "$a"
done
# special handling for station with two dcm server instances
DIR=/export/doocs/server/dcm_ctrl_39_server
if [ -d $DIR ]; then
	for a in $DIR/*.sh $DIR/*.py; do
        	chmod +x "$a"
	done
fi

