#!/bin/sh
# post remove script for the Debian GNU/Linux doocs-ulog-ctrl-server package

if [ "purge" = "$1" -o "remove" = "$1" ] ; then
   /export/doocs/server/doocs stop ulog_ctrl_server || true
fi

if [ "purge" = "$1" ] ; then
   /export/doocs/server/doocs delete ulog_ctrl_server || true
   rm -rf /export/doocs/server/ulog_ctrl_server
fi
