#!/bin/bash -e
# post install script for the Debian GNU/Linux epics-steppermotor-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
CFGDIR=/usr/share/ConfigGenerator-steppermotor-config-#epochversion# /usr/share/ConfigGenerator-#dependency-epochdashversion-doocs-llrfctrlconfig-generator# configureCurrentHost.sh steppermotor-epics
