#!/bin/sh
# post remove script for the Debian GNU/Linux doocs-dcm-ctrl-server package

if [ "purge" = "$1" -o "remove" = "$1" ] ; then
   # check if this server is already in the watchdog
   INWD=`grep "/server/dcm_ctrl_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
   if [ -n "${INWD}" ] ; then
      /export/doocs/server/doocs delete dcm_ctrl_server || true
   fi
   /export/doocs/server/doocs stop dcm_ctrl_server || true
fi

if [ "purge" = "$1" ] ; then
   rm -rf /export/doocs/server/dcm_ctrl_server
fi
