#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-llrfctrl-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

# 
# install the new server
ln -sfn /export/doocs/server/llrfCtrl_server/bin/llrfctrl /export/doocs/server/llrfCtrl_server/llrfCtrl_server

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-llrfctrl-config-08-06/configureThisHost.sh llrfctrl6
