#!/bin/bash
# post install script for the Debian GNU/Linux doocs-bam-server package

set -e

case "$1" in
    configure)
        # continue as normal
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

########## make the /export/<nodename> linl ######################
NODENAME=${NODENAME:-$(uname -n)}
UNODENAME=`echo $NODENAME | tr a-z A-Z`
POS=`expr index $UNODENAME CPU`
UFACILITY_NAME=${UNODENAME:0:POS-1}
FACILITY_NAME=${NODENAME:0:POS-1}
DOOCS_FACILITY_NAME=$UFACILITY_NAME.SDIAG
XTIMER_SERVER="$DOOCS_FACILITY_NAME/TIMER/${UNODENAME:POS+2}"
MLO_SERVER='XFEL.SYNC/MLO.LASER_LOCK/XTIN.MLO1.CONTROLLER/APP.CTRL.0.IS_ACTIVE.REG.RD'
MLO_LOCATION='XTIN.MLO1.CONTROLLER'

if [ "$FACILITY_NAME" == "xfel" ] ; then
    GID_OPERATOR=514
    GID_EXPERT=514
    if [ ! -f /export/doocs/server/bam_server/bam_motor.conf ] ; then
        echo 'MOTOR_DEVICE MD220 0 motorConfig_2xlimes60_optimal_bam.xml ""' >  /export/doocs/server/bam_server/bam_motor.conf
        echo 'MOTOR_DEVICE MD220 1 motorConfig_2xlimes60_optimal_bam.xml ""' >> /export/doocs/server/bam_server/bam_motor.conf
        echo '"" "" 0 "" ""' >> /export/doocs/server/bam_server/bam_motor.conf
        echo 'MOTOR_DEVICE MD221 1 motorConfig_2xlimes60_optimal_bam.xml ""' >> /export/doocs/server/bam_server/bam_motor.conf
    fi
    MLO_ADDRESS='XFEL.SYNC/MLO.LASER_LOCK/XTIN.MLO1.CONTROLLER'
    MLO_DEVICE='MLO.LASER_LOCK'
    MLO_LOCATION='XTIN.MLO1.CONTROLLER'
    SASE0='SAMPLE.SA1'
    SASE1='SAMPLE.SA2'
    SASE2='<redirectedRegister name="SASE.2"><targetDevice>TOROID_RAW</targetDevice><targetRegister>SAMPLE.SA3</targetRegister></redirectedRegister>'
elif [ "$FACILITY_NAME" == "flash" ] ;  then
    GID_OPERATOR=422
    GID_EXPERT=414
    MLO_DEVICE='LASER.LOCK.XLO'
    MLO_LOCATION='FLASH.MLO1'
    SASE0='SAMPLE.FLASH1'
    SASE1='SAMPLE.FLASH2'
    SASE2='<constant name="SASE.2"><type>integer</type><numberOfElements>4</numberOfElements><value index="0">0</value><value index="1">0</value><value index="2">0</value><value index="3">0</value></constant>'
fi

if [ "$NODENAME" == "xfelcpusd47i1" ] ; then
    LOCATION='47.I1'
    LINK_SERVER='XFEL.SYNC/LINK_LOCK/AMC6.CONTROLLER/LSU.2.CTRL.IS_ACTIVE.REG.RD'
    LINK_NO='2'
    LINK_LOCATION='AMC6.CONTROLLER'
    TOROID_SERVER='XFEL.DIAG/TOROID/TORA.46.I1'
    TOROID_LOCATION='TORA.46.I1'
    TOROID_DATA_THREESHOLD=0.010
    SET_PEAK_BASE_LOW_CHARGE_CHANNEL=0
    SET_PEAK_BASE_HIGH_CHARGE_CHANNEL=0
    MOTOR_CONVERSION_FACTOR='0.26067    0.26067    0.26067 0.26067'
    MOTOR_CONVERSION_REFLECTION='1    1    1    1'
    MOTOR_CONVERSION_TRANSLATION_OFFSET='0.0 0.0 0.0 0.0' 
    DELTAT_MOTOR_SIGN='1    1    1'
    DELTAT_SIGN='0.001    0.001    0'
    MODULATION_SIGN='-1.0    -1.0    -1.0'
    ARRIVAL_TIME_OFFSET=0
    START_ARRAY_VALUE_ACCURACY=10
    N_SAMPLE_ACCURACY=200
    FEEDBACK_THREESHOLD_CHARGE='0.01   0.01   0.01'
fi

if [ "$NODENAME" == "xfelcpusd181b1" ] ; then
    LOCATION='181.B1'
    LINK_SERVER='XFEL.SYNC/LINK_LOCK/AMC7.CONTROLLER/LSU.0.CTRL.IS_ACTIVE.REG.RD'
    LINK_NO='0'
    LINK_LOCATION='XFEL.SYNC/LINK_LOCK/AMC7.CONTROLLER'
    TOROID_SERVER='XFEL.DIAG/TOROID/TORA.175.B1'
    TOROID_LOCATION='XFEL.DIAG/TOROID/TORA.175.B1'
    TOROID_DATA_THREESHOLD=0.010
    SET_PEAK_BASE_LOW_CHARGE_CHANNEL=0
    SET_PEAK_BASE_HIGH_CHARGE_CHANNEL=0
    MOTOR_CONVERSION_FACTOR='0.26067    0.26067    0.26067 0.26067'
    MOTOR_CONVERSION_REFLECTION='1    1    1    1'
    MOTOR_CONVERSION_TRANSLATION_OFFSET='0.0 0.0 0.0 0.0' 
    DELTAT_MOTOR_SIGN='1    1    1'
    DELTAT_SIGN='0.001    0.001    0'
    MODULATION_SIGN='-1.0    -1.0    -1.0'
    ARRIVAL_TIME_OFFSET=0
    START_ARRAY_VALUE_ACCURACY=10
    N_SAMPLE_ACCURACY=20
    FEEDBACK_THREESHOLD_CHARGE='0.01   0.01   0.01'
fi

if [ "$NODENAME" == "xfelcpusd205b1" ] ; then
    LOCATION='203.B1'
    LINK_SERVER='XFEL.SYNC/LINK_LOCK/AMC7.CONTROLLER/LSU.1.CTRL.IS_ACTIVE.REG.RD'
    LINK_NO='1'
    LINK_LOCATION='AMC7.CONTROLLER'
    TOROID_SERVER='XFEL.DIAG/TOROID/TORA.203.B1'
    TOROID_LOCATION='TORA.203.B1'
    TOROID_DATA_THREESHOLD=0.010
    SET_PEAK_BASE_LOW_CHARGE_CHANNEL=0
    SET_PEAK_BASE_HIGH_CHARGE_CHANNEL=0
    MOTOR_CONVERSION_FACTOR='0.26067    0.26067    0.26067 0.26067'
    MOTOR_CONVERSION_REFLECTION='1    1    1    1'
    MOTOR_CONVERSION_TRANSLATION_OFFSET='0.0 0.0 0.0 0.0' 
    DELTAT_MOTOR_SIGN='1    1    1'
    DELTAT_SIGN='0.001    0.001    0'
    MODULATION_SIGN='-1.0    -1.0    -1.0'
    ARRIVAL_TIME_OFFSET=0
    START_ARRAY_VALUE_ACCURACY=10
    N_SAMPLE_ACCURACY=200
    FEEDBACK_THREESHOLD_CHARGE='0.01   0.01   0.01'
fi

if [ "$NODENAME" == "xfelcpusd392b2" ] ; then
    LOCATION='392.B2'
    LINK_SERVER='XFEL.SYNC/LINK_LOCK/AMC7.CONTROLLER/LSU.2.CTRL.IS_ACTIVE.REG.RD'
    LINK_NO='2'
    LINK_LOCATION='AMC7.CONTROLLER'
    TOROID_SERVER='XFEL.DIAG/TOROID/TORA.387.B2'
    TOROID_LOCATION='TORA.387.B2'
    TOROID_DATA_THREESHOLD=0.010
    SET_PEAK_BASE_LOW_CHARGE_CHANNEL=0
    SET_PEAK_BASE_HIGH_CHARGE_CHANNEL=0
    MOTOR_CONVERSION_FACTOR='0.26067    0.26067    0.26067 0.26067'
    MOTOR_CONVERSION_REFLECTION='1    1    1    1'
    MOTOR_CONVERSION_TRANSLATION_OFFSET='0.0 0.0 0.0 0.0' 
    DELTAT_MOTOR_SIGN='1    1    1'
    DELTAT_SIGN='0.001    0.001    0'
    MODULATION_SIGN='-1.0    -1.0    -1.0'
    ARRIVAL_TIME_OFFSET=0
    START_ARRAY_VALUE_ACCURACY=10
    N_SAMPLE_ACCURACY=200
    FEEDBACK_THREESHOLD_CHARGE='0.01   0.01   0.01'
fi

if [ "$NODENAME" == "xfelcpusd417b2" ] ; then
    LOCATION='414.B2'
    LINK_SERVER='XFEL.SYNC/LINK_LOCK/AMC7.CONTROLLER/LSU.3.CTRL.IS_ACTIVE.REG.RD'
    LINK_NO='3'
    LINK_LOCATION='AMC7.CONTROLLER'
    TOROID_SERVER='XFEL.DIAG/TOROID/TORA.387.B2'
    TOROID_LOCATION='TORA.387.B2'
    TOROID_DATA_THREESHOLD=0.010
    SET_PEAK_BASE_LOW_CHARGE_CHANNEL=0
    SET_PEAK_BASE_HIGH_CHARGE_CHANNEL=0
    MOTOR_CONVERSION_FACTOR='0.26067    0.26067    0.26067 0.26067'
    MOTOR_CONVERSION_REFLECTION='1    1    1    1'
    MOTOR_CONVERSION_TRANSLATION_OFFSET='0.0 0.0 0.0 0.0' 
    DELTAT_MOTOR_SIGN='1    1    1'
    DELTAT_SIGN='0.001    0.001    0'
    MODULATION_SIGN='-1.0    -1.0    -1.0'
    ARRIVAL_TIME_OFFSET=0
    START_ARRAY_VALUE_ACCURACY=10
    N_SAMPLE_ACCURACY=200
    FEEDBACK_THREESHOLD_CHARGE='0.01   0.01   0.01'
fi

#
# RPC_LIBNO
# 
if [ -f /export/doocs/server/bam_server/RPC_LIBNO ] ; then
    RPC_LIBNO=`cat /export/doocs/server/bam_server/RPC_LIBNO`
    export RPC_LIBNO
else
    echo 2>&1 "File: /export/doocs/server/bam_server/RPC_LIBNO is missing"
    exit 1
fi

if [ ! -f /export/doocs/server/bam_server/bam_server.conf  ] ; then
    if [ -f /export/doocs/server/bam_server/bam_CONF.TEMPLATE ] ; then
        sed /export/doocs/server/bam_server/bam_CONF.TEMPLATE \
            -e"s/LOCATION/$LOCATION/g" \
            -e "s|LINK_SERVER|$LINK_SERVER|g" \
            -e "s|MLO_SERVER|$MLO_SERVER|g" \
            -e "s|TOROID_SERVER|$TOROID_SERVER|g" \
            -e "s/GID_OPERATOR/$GID_OPERATOR/g" \
            -e "s/GID_EXPERT/$GID_EXPERT/g" \
            -e "s/DOOCS_FACILITY_NAME/$DOOCS_FACILITY_NAME/g" \
            -e "s/FACILITY_NAME/$FACILITY_NAME/g" \
            -e "s|XTIMER_SERVER|$XTIMER_SERVER|g" \
            -e "/^TOROID_DATA_THREESHOLD/s/$/$TOROID_DATA_THREESHOLD/g" \
            -e "/^SET_PEAK_BASE_LOW_CHARGE_CHANNEL/s/$/$SET_PEAK_BASE_LOW_CHARGE_CHANNEL/g" \
            -e "/^SET_PEAK_BASE_HIGH_CHARGE_CHANNEL/s/$/$SET_PEAK_BASE_HIGH_CHARGE_CHANNEL/g" \
            -e "/^MOTOR_CONVERSION_FACTOR/s/$/$MOTOR_CONVERSION_FACTOR/g" \
            -e "/^MOTOR_CONVERSION_REFLECTION/s/$/$MOTOR_CONVERSION_REFLECTION/g" \
            -e "/^MOTOR_CONVERSION_TRANSLATION_OFFSET/s/$/$MOTOR_CONVERSION_TRANSLATION_OFFSET/g" \
            -e "/^DELTAT_MOTOR_SIGN/s/$/$DELTAT_MOTOR_SIGN/g" \
            -e "/^DELTAT_SIGN/s/$/$DELTAT_SIGN/g" \
            -e "/^MODULATION_SIGN/s/$/$MODULATION_SIGN/g" \
            -e "/^ARRIVAL_TIME_OFFSET/s/$/$ARRIVAL_TIME_OFFSET/g" \
            -e "/^START_ARRAY_VALUE_ACCURACY/s/$/$START_ARRAY_VALUE_ACCURACY/g" \
            -e "/^N_SAMPLE_ACCURACY/s/$/$N_SAMPLE_ACCURACY/g" \
            -e "/^FEEDBACK_THREESHOLD_CHARGE/s/$/$FEEDBACK_THREESHOLD_CHARGE/g" \
            -e "s/NODENAME/$UNODENAME/g" \
            -e "s/nodename/$NODENAME/g" > \
            /export/doocs/server/bam_server/bam_server.conf
    fi
fi

##
## watchdog template 
##
if [ ! -f /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.bam  ] ; then
    if [ -f /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE ] ; then
        sed /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.TEMPLATE \
            -e "s/NODENAME/$UNODENAME/g" \
            -e "s/nodename/$NODENAME/g" \
            -e "s/servername/bam_server/g" \
            -e "s/SERVERNAME/BAM/g" \
            -e "s/SERVERLIBNO/$RPC_LIBNO/g" > \
            /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.bam
        chown doocsadm:doocsadm /export/doocs/server/watchdog_server/WATCHDOG_CONF_ENTRY.bam
    fi
fi 

##
## ens
##
echo "add server to ens "
echo "RPC_LIBNO = $RPC_LIBNO"

# create files for the lookup tables from templates
if [ ! -f /export/doocs/server/bam_server/high_charge_look_up_table.txt ] ; then
    cp /export/doocs/server/bam_server/high_charge_look_up_table.txt.template \
        /export/doocs/server/bam_server/high_charge_look_up_table.txt
fi

if [ ! -f /export/doocs/server/bam_server/low_charge_look_up_table.txt ] ; then
    cp /export/doocs/server/bam_server/low_charge_look_up_table.txt.template \
        /export/doocs/server/bam_server/low_charge_look_up_table.txt
fi

#
# create dmap file from template
if [ ! -f /export/doocs/server/bam_server/BAM.dmap ] ; then
    sed /export/doocs/server/bam_server/BAM.dmap.template \
        -e "s#@ACCELERATOR@#${ULOCATION}#" \
        -e "s#@TOROID_LOCATION@#${TOROID_SERVER}#" \
        -e "s#@LINK_LOCATION@#${LINK_ADDRESS}#" \
        -e "s#@MLO_DEVICE@#${MLO_DEVICE}#" \
        -e "s#@MLO_LOCATION@#${MLO_LOCATION}#" \
        > /export/doocs/server/bam_server/BAM.dmap
fi

#
# create toroid name mapper config
if [ ! -f /export/doocs/server/bam_server/toroid.xlmap ] ; then
    sed /export/doocs/server/bam_server/toroid.xlmap.template \
        -e "s/@SASE0@/${SASE0}/g" \
        -e "s/@SASE1@/${SASE1}/g" \
        -e "s#@SASE2@#${SASE2}#g" \
        > /export/doocs/server/bam_server/toroid.xlmap
fi

# create link name mapper config
if [ ! -f /export/doocs/server/bam_server/link_lock.xlmap ] ; then
    sed /export/doocs/server/bam_server/link_lock.xlmap.template \
        -e "s/@LINK_LOCK_NUMBER@/${LINK_NO}/g" \
        > /export/doocs/server/bam_server/link_lock.xlmap
fi


# 
# install the new server, moving the old server to .OLD and ensuring proper ownership
install --backup --suffix=.OLD -m 755 -o doocsadm -g doocsadm \
    /export/doocs/server/bam_server/bam_server.dist \
    /export/doocs/server/bam_server/bam_server


#
# check if this server is already in the watchdog
INWD=`grep "/server/bam_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`

if [ -z "${INWD}" ] ; then
    /export/doocs/server/doocs add bam_server || true
fi

#
# kill the server if there is a valid PID file and 
# a AUTORESTART flag in the server dir
if [ -f /export/doocs/server/bam_server/bam_server.PID ] ; then
    SPID=`cat /export/doocs/server/bam_server/bam_server.PID`
    if [ -d /proc/${SPID} ] ; then
        /export/doocs/server/doocs restart bam_server
    else
        echo "bam_server: postinstall remove not valid PID file"
        rm /export/doocs/server/bam_server/bam_server.PID
    fi
fi

