#!/bin/sh
# post remove script for the Debian GNU/Linux doocs-llrf-diagnostic-server package

if [ "purge" = "$1" -o "remove" = "$1" ] ; then
   /export/doocs/server/doocs stop optical_switch_server || true
fi

if [ "purge" = "$1" ] ; then
   /export/doocs/server/doocs delete optical_switch_server || true
   rm -rf /export/doocs/server/optical_switch_server
fi
