#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-lam-frontend-server package

#set -e

case "$1" in
  configure)
    # continue as normal
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0;
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2;
    exit 0;
  ;;
esac

# 
# install the new server
ln -snf /export/doocs/server/lam_frontend_server/lam_frontend_server.dist /export/doocs/server/lam_frontend_server/lam_frontend_server

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-lam-frontend-config-01-00/configureThisHost.sh lam-frontend
