#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-bam-server package

set -e

case "$1" in
    configure)
        # continue as normal
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0;
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
        ;;
esac

#
# install the new server
if [ -e /export/doocs/server/bam_server/bam_server.dist ];
then
    ln -snf /export/doocs/server/bam_server/bam_server.dist /export/doocs/server/bam_server/bam_server
fi

#
# generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
/usr/share/ConfigGenerator-bam-config-03-03/configureThisHost.sh bam
