#!/bin/sh
# post remove script for the Debian GNU/Linux doocs-modperf-server package

if [ "purge" = "$1" -o "remove" = "$1" ] ; then
   # check if this server is already in the watchdog
   INWD=`grep "/server/mod_perf_server/" /export/doocs/server/watchdog_server/watchdog_server.conf || true`
   if [ -n "${INWD}" ] ; then
      /export/doocs/server/doocs delete mod_perf_server || true
   fi
   /export/doocs/server/doocs stop mod_perf_server || true
fi

if [ "purge" = "$1" ] ; then
   rm -rf /export/doocs/server/mod_perf_server
fi
