#!/bin/bash -e
# post install script for the Debian GNU/Linux doocs-qlset-server package

set -e

case "$1" in
	configure)
		# continue as normal
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2;
		exit 0;
	;;
esac

########## make the /export/<nodename> linl ######################
NODENAME=`uname -n`
UNODENAME=`uname -n | sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" `

#
# RPC_LIBNO
# 
if [ -f /export/doocs/server/qlset_server/RPC_LIBNO ] ; then
RPC_LIBNO=`cat /export/doocs/server/qlset_server/RPC_LIBNO`
export RPC_LIBNO
else
  echo 2>&1 "File: /export/doocs/server/qlset_server/RPC_LIBNO is missing"
  exit 1
fi
#
# move the running server to old
if [ -f /export/doocs/server/qlset_server/qlset_server ] ; then
   if [ -f /export/doocs/server/qlset_server/qlset_server.OLD ] ; then
      rm /export/doocs/server/qlset_server/qlset_server.OLD
   fi
   mv /export/doocs/server/qlset_server/qlset_server /export/doocs/server/qlset_server/qlset_server.OLD
fi
# 
# install the new server
cp -a /export/doocs/server/qlset_server/qlset_server.dist /export/doocs/server/qlset_server/qlset_server

# generate and/or update configuration files
/usr/share/ConfigGenerator-qlset-config-01-02/configureThisHost.sh qlset
