#!/bin/sh
if [ "purge" = "$1" ] ; then
	if [ -e "/var/lib/chimeratk/watchdog-server/WatchdogServer.persist" ]; then
	#do not remove the directory since it is removed by apt
	#just delete files that are added after installation 
	  rm /var/lib/chimeratk/watchdog-server/WatchdogServer.persist
	  rm /var/lib/chimeratk/watchdog-server/WatchdogServer_mapping.xml
	  rm /var/lib/chimeratk/watchdog-server/WatchdogServerConfig.xml
	  find /var/lib/chimeratk/watchdog-server/ -iname "*.log" -delete
    fi
    if [ -d "/etc/chimeratk/watchdog-server" ]; then
      rm -fr /etc/chimeratk/watchdog-server
    fi
    if [ -e "/var/lib/chimeratk/watchdog-server/uDAQ" ]; then
    	rm -fr /var/lib/chimeratk/watchdog-server/uDAQ
    fi
fi