#!/bin/sh
# post install script for the ChimeraTK watchdog package

# create links to config files that are needed for running the server
if [[ -e "/etc/chimeratk/watchdog-server/WatchdogServer_mapping.xml" && ! -e "/var/lib/chimeratk/watchdog-server/WatchdogServer_mapping.xml" ]]; then
	ln -s /etc/chimeratk/watchdog-server/WatchdogServer_mapping.xml /var/lib/chimeratk/watchdog-server/
fi
if [[ -e "/etc/chimeratk/watchdog-server/WatchdogServer_processes.xml" && ! -e "/var/lib/chimeratk/watchdog-server/WatchdogServer_processes.xml" ]]; then
	ln -s /etc/chimeratk/watchdog-server/WatchdogServer_processes.xml /var/lib/chimeratk/watchdog-server/
fi

if [ -d "/lib/systemd/system" -a -x "/bin/systemctl" ] ; then
   systemctl daemon-reload
   # no need to perform stop or disable before, since with every installation an old version is uninstalled and prerm is executed 
   systemctl enable /var/lib/chimeratk/watchdog-server/chimeratk-watchdog.service
   systemctl start chimeratk-watchdog.service
fi

#create variable tree file
cd /etc/chimeratk/watchdog-server/
/usr/bin/watchdog-server-xmlGenerator


