#!/bin/sh
if [ "purge" = "$1" ] ; then
	#do not remove the directory since it is removed by apt
	#just delete files that are added after installation 

    if [ -e "/etc/chimeratk/watchdog-server/WatchdogServer.xml" ]; then
      rm /etc/chimeratk/watchdog-server/WatchdogServer.xml
    fi
    
    if [ -e "/etc/chimeratk/watchdog-server/WatchdogServer.persist" ]; then
      rm /etc/chimeratk/watchdog-server/WatchdogServer.persist
    fi
fi

#remove runtime directory and files
if [ -e "/var/lib/chimeratk/watchdog-server/keep_daq" ]; then
	find /var/lib/chimeratk/watchdog-server/* -iname "*"  ! -iname "uDAQ" -delete
	echo "Found existing uDAQ during upgrade step."
else
     if [ -d "/var/lib/chimeratk/watchdog-server" ]; then
	rm -r /var/lib/chimeratk/watchdog-server
     fi
fi
if [ -d "/var/lib/chimeratk/" ] && [ -z "$(ls -A /var/lib/chimeratk/)" ]; then
	rm -r /var/lib/chimeratk
fi
