#!/bin/sh
if [ -d "/lib/systemd/system" -a -x "/bin/systemctl" ] ; then
   systemctl stop chimeratk-watchdog.service
   systemctl disable chimeratk-watchdog.service
fi

# copy persist file to config file folder, since it used to store information like PIDs and configuration settings
if [ -e "/var/lib/chimeratk/watchdog-server/WatchdogServer.persist" ]; then
	cp /var/lib/chimeratk/watchdog-server/WatchdogServer.persist /etc/chimeratk/watchdog-server/
fi